//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubbyBook.Web.Common {
    
    
    public partial class Default {
        
        /// <summary>
        /// contentHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ClubbyBook.Web.Controls.ContentHeaderControl contentHeader;
        
        /// <summary>
        /// topNewsContentHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ClubbyBook.Web.Controls.ContentHeaderControl topNewsContentHeader;
        
        /// <summary>
        /// recommendedBooksContentHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ClubbyBook.Web.Controls.ContentHeaderControl recommendedBooksContentHeader;
        
        /// <summary>
        /// latestBooksHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ClubbyBook.Web.Controls.ContentHeaderControl latestBooksHeader;
        
        /// <summary>
        /// mostPopularBooksOnSaleContentHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ClubbyBook.Web.Controls.ContentHeaderControl mostPopularBooksOnSaleContentHeader;
        
        /// <summary>
        /// mostPopularBooksInExchangeContentHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ClubbyBook.Web.Controls.ContentHeaderControl mostPopularBooksInExchangeContentHeader;
    }
}
